 # versions below are pinned just so they can work on Vitor's cloud desktop. 
 # we can unpin / make them flexible before an official release.

[project]
name = "rlvr-experiments"
requires-python = ">=3.11,<3.12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "torch==2.6.0+cu124",
    "torchtitan==0.2.0",
    "vllm==0.8.5.post1",
    "numpy==1.26.4",
    "pyarrow==19.0.1",
]

[tool.uv]
package = true

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
xformers = { index = "pytorch" } 

[project.scripts]
run_inference = "entrypoints.inference:main"
run_training = "entrypoints.training:main"