[project]
name = "rlvr-experiments"
requires-python = ">=3.11,<3.12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "torch",
    "torchtitan",
    "vllm",
    "fastapi>=0.123.0",
    "uvicorn>=0.38.0",
    "omegaconf>=2.3.0",
    "openai>=2.8.1",
]

[tool.uv]
package = true

[project.scripts]
run_inference = "entrypoints.inference:main"
run_training = "entrypoints.training:main"
